'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DetailOrder
    Public Property DetailId As Integer
    Public Property OrderId As String
    Public Property MenuId As Integer
    Public Property Qty As Integer
    Public Property Price As Integer
    Public Property Status As String

    Public Overridable Property HeaderOrder As HeaderOrder
    Public Overridable Property MsMenu As MsMenu

End Class
