'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HeaderOrder
    Public Property OrderId As String
    Public Property EmployeeId As String
    Public Property MemberId As String
    Public Property [Date] As Date
    Public Property Payment As String
    Public Property Bank As String
    Public Property CardNumber As String
    Public Property TableId As Integer

    Public Overridable Property DetailOrders As ICollection(Of DetailOrder) = New HashSet(Of DetailOrder)
    Public Overridable Property MsEmployee As MsEmployee
    Public Overridable Property MsMember As MsMember
    Public Overridable Property MsTable As MsTable

End Class
