'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MenuDetail
    Public Property Name As String
    Public Property Qty As Integer
    Public Property Price As Integer
    Public Property Total As Integer
    Public Property OrderId As String

End Class
