'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MsEmployee
    Public Property EmployeeId As String
    Public Property Name As String
    Public Property Email As String
    Public Property Password As String
    Public Property Handphone As String
    Public Property Position As String

    Public Overridable Property HeaderOrders As ICollection(Of HeaderOrder) = New HashSet(Of HeaderOrder)

End Class
