'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class RestaurantSMKEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=RestaurantSMKEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property DetailOrders() As DbSet(Of DetailOrder)
    Public Overridable Property HeaderOrders() As DbSet(Of HeaderOrder)
    Public Overridable Property MsEmployees() As DbSet(Of MsEmployee)
    Public Overridable Property MsMembers() As DbSet(Of MsMember)
    Public Overridable Property MsMenus() As DbSet(Of MsMenu)
    Public Overridable Property MsTables() As DbSet(Of MsTable)
    Public Overridable Property MenuDetails() As DbSet(Of MenuDetail)
    Public Overridable Property SelectMembers() As DbSet(Of SelectMember)

End Class
